name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: extractions/setup-just@v2

      - uses: leanprover/lean-action@v1
        with:
          auto-config: false

      - name: query clang
        run: clang --version

      - uses: actions/checkout@v3

      - name: build project
        run: just build
