name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: extractions/setup-just@v2

      - name: Setup Rust
        run: rustup toolchain install stable --profile minimal

      - name: install elan
        run: |
            set -o pipefail
            curl -sSfL https://github.com/leanprover/elan/releases/download/v3.1.1/elan-aarch64-apple-darwin.tar.gz | tar xz
            ./elan-init -y --no-modify-path --default-toolchain none
            echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: query clang
        run: clang --version

      - uses: actions/checkout@v4

      - name: build project
        run: just build

      - name: create release tarball
        run: |
          tar zcf raylib-lean_macos-aarch64.tar.gz -C .lake/build/bin raylib-lean

      - uses: actions/upload-artifact@v4
        with:
          name: macos-aarch64-binary
          path: raylib-lean_macos-aarch64.tar.gz
          if-no-files-found: error
